[package]
name = "webdav-sync"
version = "0.2.0"
edition = "2018"
authors = ["Tom Weissinger"]

[dependencies]
notify = "7.0.0"
notify-debouncer-full = "0.4.0"
rustydav = "0.1.3"
clap = { version = "4.5.21", features = ["derive"] }
proc-macro2 = "1.0.92"
